export const ROUTES={
    LOGIN:"/login",
    DASHBOARD:"/",
    PRODUCT:{
        LIST:"/products",
        CREATE:"/product-create",
        EDIT:"/product-edit"
    },
    CATEGORY:{
        LIST:"/categories"
    },
    BRAND:{
        LIST:"/brands"
    },
    USER:{
        LIST:"/users"
    },
    ORDER:{
        LIST:"/orders"
    },
    STORE_DATA:{
        LIST:"/store-data",
        EDIT:"/store-data-edit"
    },
    SLIDER:{
        LIST:"/sliders"
    },
   
}